// Copyright 2026 RSKGroup, LLC.
// SPDX-License-Identifier: Apache-2.0

package tdstest

// INFORMATION_SCHEMA.* views: column contract on every backend, empty-degrade for data-dependent views,
// and the concept-free views (DOMAINS, ROUTINE_COLUMNS) must be empty.
var infoschemaCases = []Case{
	{Element: "infoschema:TABLES", SQL: "SELECT * FROM INFORMATION_SCHEMA.TABLES", Check: wantCols("TABLE_CATALOG", "TABLE_NAME", "TABLE_TYPE")},
	{Element: "infoschema:COLUMNS", SQL: "SELECT * FROM INFORMATION_SCHEMA.COLUMNS", Check: wantCols("TABLE_NAME", "COLUMN_NAME", "ORDINAL_POSITION", "DATA_TYPE")},
	{Element: "infoschema:VIEWS", SQL: "SELECT * FROM INFORMATION_SCHEMA.VIEWS", Check: wantCols("TABLE_NAME", "VIEW_DEFINITION")},
	{Element: "infoschema:ROUTINES", SQL: "SELECT * FROM INFORMATION_SCHEMA.ROUTINES", Check: wantCols("ROUTINE_NAME", "ROUTINE_TYPE", "ROUTINE_DEFINITION")},
	{Element: "infoschema:PARAMETERS", SQL: "SELECT * FROM INFORMATION_SCHEMA.PARAMETERS", Check: wantCols("SPECIFIC_NAME", "PARAMETER_NAME", "ORDINAL_POSITION")},
	{Element: "infoschema:TABLE_CONSTRAINTS", SQL: "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS", Check: wantCols("CONSTRAINT_NAME", "TABLE_NAME", "CONSTRAINT_TYPE")},
	{Element: "infoschema:KEY_COLUMN_USAGE", SQL: "SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE", Check: wantCols("CONSTRAINT_NAME", "TABLE_NAME", "COLUMN_NAME", "ORDINAL_POSITION")},
	{Element: "infoschema:REFERENTIAL_CONSTRAINTS", SQL: "SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS", Check: wantCols("CONSTRAINT_NAME", "UNIQUE_CONSTRAINT_NAME", "UPDATE_RULE", "DELETE_RULE")},
	{Element: "infoschema:SCHEMATA", SQL: "SELECT * FROM INFORMATION_SCHEMA.SCHEMATA", Check: checks(wantCols("CATALOG_NAME", "SCHEMA_NAME", "SCHEMA_OWNER"), atLeastRows(1))},
	{Element: "infoschema:CHECK_CONSTRAINTS", SQL: "SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS", Check: wantCols("CONSTRAINT_NAME", "CHECK_CLAUSE")},
	{Element: "infoschema:CONSTRAINT_COLUMN_USAGE", SQL: "SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE", Check: wantCols("TABLE_NAME", "COLUMN_NAME", "CONSTRAINT_NAME")},
	{Element: "infoschema:VIEW_TABLE_USAGE", SQL: "SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE", Check: wantCols("VIEW_NAME", "TABLE_NAME")},
	{Element: "infoschema:VIEW_COLUMN_USAGE", SQL: "SELECT * FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE", Check: wantCols("VIEW_NAME", "TABLE_NAME", "COLUMN_NAME")},
	{Element: "infoschema:ROUTINE_COLUMNS", SQL: "SELECT * FROM INFORMATION_SCHEMA.ROUTINE_COLUMNS", Check: checks(wantCols("TABLE_NAME", "COLUMN_NAME"), exactRows(0))},
	{Element: "infoschema:CONSTRAINT_TABLE_USAGE", SQL: "SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE", Check: wantCols("TABLE_NAME", "CONSTRAINT_NAME")},
	{Element: "infoschema:DOMAINS", SQL: "SELECT * FROM INFORMATION_SCHEMA.DOMAINS", Check: checks(wantCols("DOMAIN_NAME", "DATA_TYPE"), exactRows(0))},
}
