// Copyright 2026 RSKGroup, LLC.
// SPDX-License-Identifier: Apache-2.0

package tdstest

// Each sys.* view asserts its column contract on every backend; data-dependent views leave row count
// open (empty-degrade), static catalogs pin an exact count, and concept-free views must be empty.
var sysviewCases = []Case{
	{Element: "sys:databases", SQL: "SELECT * FROM sys.databases", Check: checks(wantCols("name", "database_id", "state_desc"), atLeastRows(1))},
	{Element: "sys:configurations", SQL: "SELECT value_in_use FROM sys.configurations WHERE configuration_id = 16384", Check: checks(wantCols("value_in_use"), exactRows(1))},
	{Element: "sys:schemas", SQL: "SELECT * FROM sys.schemas", Check: checks(wantCols("name", "schema_id"), atLeastRows(1))},
	{Element: "sys:tables", SQL: "SELECT * FROM sys.tables", Check: wantCols("name", "object_id", "type_desc")},
	{Element: "sys:objects", SQL: "SELECT * FROM sys.objects", Check: wantCols("name", "object_id", "type_desc")},
	{Element: "sys:all_objects", SQL: "SELECT * FROM sys.all_objects", Check: wantCols("name", "object_id")},
	{Element: "sys:views", SQL: "SELECT * FROM sys.views", Check: wantCols("name", "object_id")},
	{Element: "sys:procedures", SQL: "SELECT * FROM sys.procedures", Check: wantCols("name", "object_id")},
	{Element: "sys:sql_modules", SQL: "SELECT * FROM sys.sql_modules", Check: wantCols("object_id", "definition")},
	{Element: "sys:parameters", SQL: "SELECT * FROM sys.parameters", Check: wantCols("object_id", "name", "parameter_id")},
	{Element: "sys:columns", SQL: "SELECT * FROM sys.columns", Check: wantCols("object_id", "name", "column_id")},
	{Element: "sys:all_columns", SQL: "SELECT * FROM sys.all_columns", Check: wantCols("object_id", "name", "column_id")},
	{Element: "sys:types", SQL: "SELECT * FROM sys.types", Check: checks(wantCols("name", "system_type_id", "schema_id"), exactRows(20))},
	{Element: "sys:foreign_keys", SQL: "SELECT * FROM sys.foreign_keys", Check: wantCols("name", "object_id", "referenced_object_id")},
	{Element: "sys:indexes", SQL: "SELECT * FROM sys.indexes", Check: wantCols("object_id", "name", "index_id")},
	{Element: "sys:index_columns", SQL: "SELECT * FROM sys.index_columns", Check: wantCols("object_id", "index_id", "column_id")},
	{Element: "sys:key_constraints", SQL: "SELECT * FROM sys.key_constraints", Check: wantCols("name", "object_id", "unique_index_id")},
	{Element: "sys:foreign_key_columns", SQL: "SELECT * FROM sys.foreign_key_columns", Check: wantCols("constraint_object_id", "parent_object_id", "referenced_object_id")},
	{Element: "sys:check_constraints", SQL: "SELECT * FROM sys.check_constraints", Check: wantCols("name", "definition")},
	{Element: "sys:default_constraints", SQL: "SELECT * FROM sys.default_constraints", Check: wantCols("name", "definition")},
	{Element: "sys:identity_columns", SQL: "SELECT * FROM sys.identity_columns", Check: wantCols("object_id", "name", "is_identity")},
	{Element: "sys:computed_columns", SQL: "SELECT * FROM sys.computed_columns", Check: wantCols("object_id", "name", "definition")},
	{Element: "sys:sql_expression_dependencies", SQL: "SELECT * FROM sys.sql_expression_dependencies", Check: wantCols("referencing_id", "referenced_entity_name")},
	{Element: "sys:triggers", SQL: "SELECT * FROM sys.triggers", Check: wantCols("name", "object_id", "parent_id")},
	{Element: "sys:extended_properties", SQL: "SELECT * FROM sys.extended_properties", Check: checks(wantCols("class", "name"), exactRows(0))},
	{Element: "sys:sequences", SQL: "SELECT * FROM sys.sequences", Check: checks(wantCols("name", "object_id"), exactRows(0))},
	{Element: "sys:synonyms", SQL: "SELECT * FROM sys.synonyms", Check: checks(wantCols("name", "base_object_name"), exactRows(0))},
	{Element: "sys:sysobjects", SQL: "SELECT * FROM sys.sysobjects", Check: wantCols("name", "id", "xtype")},
	{Element: "sys:syscolumns", SQL: "SELECT * FROM sys.syscolumns", Check: wantCols("name", "id", "colid")},
	{Element: "sys:systypes", SQL: "SELECT * FROM sys.systypes", Check: checks(wantCols("name", "xtype"), exactRows(20))},
	{Element: "sys:table_types", SQL: "SELECT * FROM sys.table_types", Check: wantCols("name", "type_table_object_id")},
	{Element: "sys:database_principals", SQL: "SELECT * FROM sys.database_principals", Check: checks(wantCols("name", "principal_id"), atLeastRows(1))},
	{Element: "sys:server_principals", SQL: "SELECT * FROM sys.server_principals", Check: checks(wantCols("name", "principal_id"), atLeastRows(1))},
	{Element: "sys:database_role_members", SQL: "SELECT * FROM sys.database_role_members", Check: checks(wantCols("role_principal_id", "member_principal_id"), exactRows(0))},
	{Element: "sys:sysusers", SQL: "SELECT * FROM sys.sysusers", Check: checks(wantCols("uid", "name"), atLeastRows(1))},
	{Element: "sys:sysindexes", SQL: "SELECT * FROM sys.sysindexes", Check: wantCols("id", "name", "indid")},
	{Element: "sys:database_permissions", SQL: "SELECT * FROM sys.database_permissions", Check: checks(wantCols("permission_name", "state_desc"), exactRows(0))},
	{Element: "sys:server_permissions", SQL: "SELECT * FROM sys.server_permissions", Check: checks(wantCols("permission_name", "state_desc"), exactRows(0))},
	{Element: "sys:system_objects", SQL: "SELECT * FROM sys.system_objects", Check: checks(wantCols("name", "object_id"), exactRows(0))},
	{Element: "sys:stats", SQL: "SELECT * FROM sys.stats", Check: checks(wantCols("object_id", "stats_id", "name"), exactRows(0))},
	{Element: "sys:stats_columns", SQL: "SELECT * FROM sys.stats_columns", Check: checks(wantCols("object_id", "stats_id", "column_id"), exactRows(0))},
	{Element: "sys:partitions", SQL: "SELECT * FROM sys.partitions", Check: wantCols("object_id", "index_id", "partition_number", "rows")},
	{Element: "sys:database_files", SQL: "SELECT * FROM sys.database_files", Check: checks(wantCols("file_id", "name", "type_desc"), exactRows(1))},
	{Element: "sys:filegroups", SQL: "SELECT * FROM sys.filegroups", Check: checks(wantCols("name", "is_default"), exactRows(1))},
	{Element: "sys:dm_exec_sessions", SQL: "SELECT * FROM sys.dm_exec_sessions", Check: checks(wantCols("session_id", "login_name", "host_name"), exactRows(0))},
	{Element: "sys:dm_exec_connections", SQL: "SELECT * FROM sys.dm_exec_connections", Check: checks(wantCols("session_id", "net_transport", "client_net_address"), exactRows(0))},
	{Element: "sys:dm_exec_requests", SQL: "SELECT * FROM sys.dm_exec_requests", Check: checks(wantCols("session_id", "status", "command"), exactRows(0))},
	{Element: "sys:dm_exec_query_stats", SQL: "SELECT * FROM sys.dm_exec_query_stats", Check: checks(wantCols("execution_count", "total_worker_time"), exactRows(0))},
	{Element: "sys:dm_os_waiting_tasks", SQL: "SELECT * FROM sys.dm_os_waiting_tasks", Check: checks(wantCols("session_id", "wait_type", "wait_duration_ms"), exactRows(0))},
	{Element: "sys:dm_os_host_info", SQL: "SELECT * FROM sys.dm_os_host_info", Check: checks(wantCols("host_platform"), exactRows(1))},
	{Element: "sys:internal_tables", SQL: "SELECT * FROM sys.internal_tables", Check: checks(wantCols("object_id", "name", "parent_object_id"), exactRows(0))},
	{Element: "sys:data_spaces", SQL: "SELECT * FROM sys.data_spaces", Check: checks(wantCols("name", "data_space_id", "type_desc"), exactRows(1))},
	{Element: "sys:partition_schemes", SQL: "SELECT * FROM sys.partition_schemes", Check: checks(wantCols("name", "data_space_id", "function_id"), exactRows(0))},
	{Element: "sys:xml_schema_collections", SQL: "SELECT * FROM sys.xml_schema_collections", Check: checks(wantCols("xml_collection_id", "name"), exactRows(0))},
	{Element: "sys:column_encryption_keys", SQL: "SELECT * FROM sys.column_encryption_keys", Check: checks(wantCols("column_encryption_key_id", "name"), exactRows(0))},
	{Element: "sys:masked_columns", SQL: "SELECT * FROM sys.masked_columns", Check: checks(wantCols("object_id", "column_id", "is_masked"), exactRows(0))},
	{Element: "sys:xml_indexes", SQL: "SELECT * FROM sys.xml_indexes", Check: checks(wantCols("object_id", "index_id", "name"), exactRows(0))},
	{Element: "sys:spatial_indexes", SQL: "SELECT * FROM sys.spatial_indexes", Check: checks(wantCols("object_id", "index_id", "name"), exactRows(0))},
	{Element: "sys:assembly_modules", SQL: "SELECT * FROM sys.assembly_modules", Check: checks(wantCols("object_id", "assembly_id"), exactRows(0))},
	{Element: "sys:trigger_events", SQL: "SELECT * FROM sys.trigger_events", Check: checks(wantCols("object_id", "type_desc"), exactRows(0))},
	{Element: "sys:system_sql_modules", SQL: "SELECT * FROM sys.system_sql_modules", Check: checks(wantCols("object_id", "definition"), exactRows(0))},
	{Element: "sys:master_files", SQL: "SELECT * FROM sys.master_files", Check: checks(wantCols("database_id", "file_id", "type_desc"), exactRows(0))},
	{Element: "sys:partition_functions", SQL: "SELECT * FROM sys.partition_functions", Check: checks(wantCols("name", "function_id"), exactRows(0))},
	{Element: "sys:partition_range_values", SQL: "SELECT * FROM sys.partition_range_values", Check: checks(wantCols("function_id", "boundary_id"), exactRows(0))},
	{Element: "sys:partition_parameters", SQL: "SELECT * FROM sys.partition_parameters", Check: checks(wantCols("function_id", "parameter_id"), exactRows(0))},
	{Element: "sys:destination_data_spaces", SQL: "SELECT * FROM sys.destination_data_spaces", Check: checks(wantCols("partition_scheme_id", "data_space_id"), exactRows(0))},
	{Element: "sys:allocation_units", SQL: "SELECT * FROM sys.allocation_units", Check: checks(wantCols("allocation_unit_id", "type_desc", "total_pages"), exactRows(0))},
	{Element: "sys:dm_db_partition_stats", SQL: "SELECT * FROM sys.dm_db_partition_stats", Check: checks(wantCols("partition_id", "object_id", "row_count"), exactRows(0))},
	{Element: "sys:availability_replicas", SQL: "SELECT * FROM sys.availability_replicas", Check: checks(wantCols("replica_id", "group_id", "replica_server_name"), exactRows(0))},
	{Element: "sys:availability_groups", SQL: "SELECT * FROM sys.availability_groups", Check: checks(wantCols("group_id", "name"), exactRows(0))},
	{Element: "sys:dm_hadr_database_replica_states", SQL: "SELECT * FROM sys.dm_hadr_database_replica_states", Check: checks(wantCols("group_database_id", "database_id", "is_local"), exactRows(0))},
	{Element: "sys:database_mirroring", SQL: "SELECT * FROM sys.database_mirroring", Check: checks(wantCols("database_id", "mirroring_role"), exactRows(0))},
	{Element: "sys:dm_hadr_cluster", SQL: "SELECT * FROM sys.dm_hadr_cluster", Check: checks(wantCols("cluster_name", "quorum_type"), exactRows(0))},
	{Element: "sys:dm_hadr_availability_replica_states", SQL: "SELECT * FROM sys.dm_hadr_availability_replica_states", Check: checks(wantCols("replica_id", "role", "synchronization_health"), exactRows(0))},
	{Element: "sys:dm_hadr_availability_group_states", SQL: "SELECT * FROM sys.dm_hadr_availability_group_states", Check: checks(wantCols("group_id", "primary_replica"), exactRows(0))},
}
